/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#f9f9ff',
        surface: '#f9f9ff',
        'surface-dim': '#d3daef',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f3ff',
        'surface-container': '#e9edff',
        'surface-container-high': '#e1e8fd',
        'surface-container-highest': '#dce2f7',
        'surface-variant': '#dce2f7',
        'surface-tint': '#345baf',
        primary: '#002869',
        'primary-container': '#0b3d91',
        'primary-fixed': '#dae2ff',
        'primary-fixed-dim': '#b1c5ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#8dadff',
        'on-primary-fixed': '#001947',
        'on-primary-fixed-variant': '#144296',
        secondary: '#9d4300',
        'secondary-container': '#fd761a',
        'secondary-fixed': '#ffdbca',
        'secondary-fixed-dim': '#ffb690',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5c2400',
        'on-secondary-fixed': '#341100',
        'on-secondary-fixed-variant': '#783200',
        tertiary: '#00227a',
        'tertiary-container': '#0f36a6',
        'tertiary-fixed': '#dde1ff',
        'tertiary-fixed-dim': '#b8c4ff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#97abff',
        'on-tertiary-fixed': '#001453',
        'on-tertiary-fixed-variant': '#173bab',
        'on-background': '#141b2b',
        'on-surface': '#141b2b',
        'on-surface-variant': '#434652',
        'inverse-surface': '#293040',
        'inverse-on-surface': '#edf0ff',
        'inverse-primary': '#b1c5ff',
        outline: '#747783',
        'outline-variant': '#c4c6d3',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '20px',
        'sidebar-width': '260px',
        'container-max': '1440px',
      },
      fontFamily: {
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        h1: ['Inter', 'system-ui', 'sans-serif'],
        h2: ['Inter', 'system-ui', 'sans-serif'],
        h3: ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        h1: ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
